import type { NextPage } from "next";
import Head from "next/head";
import Main from "../components/Main";
import SidebarLeft from "../components/SidebarLeft";
import SidebarRight from "../components/SidebarRight";
import styles from "../styles/Home.module.css";
import { UserContext } from "../components/UserContext";
import { useEffect, useMemo, useState } from "react";

interface HomeProps {}

const Home: NextPage<HomeProps> = () => {
  const [user, setUser] = useState("");

  // TODO: the context and login functionality need to be linked
  // so we don't individually set local storage and setUser
  useEffect(() => {
    const checkTokenValidity = async (token: string) => {
      // TODO: we need to remove the token if it's past expiry
      // check EXPIRATION is on client side, SO WE NEED TO
      // check and delete session data here after checking expiry
      // time from our login data
      // TODO: implement getExpiration();
      // otherwise logout and redirect to homepage
    };

    // Check if logged in
    const token = localStorage.getItem("token");

    if (!token) return;

    // Authorise token
    checkTokenValidity(token);
  }, []);

  // Prevent provider value from changing unless value actually changes
  const value = useMemo(() => ({ user, setUser }), [user, setUser]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Chirp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main}>
        {/* <UserContext.Provider value={{ user, setUser }}> */}
        <UserContext.Provider value={value}>
          <SidebarLeft />
          <Main />
          <SidebarRight />
        </UserContext.Provider>
      </div>
    </div>
  );
};

export default Home;
