import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import Main from "../components/Main";
import SidebarLeft from "../components/SidebarLeft";
import SidebarRight from "../components/SidebarRight";
import styles from "../styles/Home.module.css";

interface HomeProps {}

const Home: NextPage<HomeProps> = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Chirper</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main}>
        <SidebarLeft />
        <Main />
        <SidebarRight />
      </div>
    </div>
  );
};

// export const getServerSideProps: GetServerSideProps = async (context) => {
//   const res = await fetch("");
//   const { results } = await res.json();

//   return {
//     props: {
//       characters: results,
//     },
//   };
// };

export default Home;
